{% set name = "bjoern" %}
{% set version = "3.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 16e5a02a9a17a7f5f8bea0d7c58650e78ab80ead6fe3e390037573d4355baf31

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - libev
  run:
    - python
    - libev

test:
  imports:
    - bjoern

about:
  home: https://github.com/jonashaag/bjoern
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A screamingly fast Python 2/3 WSGI server written in C.
  description: |
    A screamingly fast, ultra-lightweight WSGI server for CPython 2 and CPython
    3, written in C using Marc Lehmann's high performance
    `libev <http://software.schmorp.de/pkg/libev.html>`_ event loop and Ryan
    Dahl's `http-parser <https://github.com/joyent/http-parser>`_.
  dev_url: https://github.com/jonashaag/bjoern

extra:
  recipe-maintainers:
    - carlodri
