travis:
  secure:
    BINSTAR_TOKEN: RjuF0Gsbwh4SlW2ZQArSvETUExHE/+gcYRFfFl8PWQc+ZvmaoBJJuHjAOK5Eh49LLxjQWOvlXVRUzgO9+HewZrnMs3Grusd4D8JQGd32cw2Kec5HJDcPExvvWTE5yC3P9029+H/MnxHd55NIvqD64fTuHDtl6jVEA/KJaQL83YrV/9MQ7AtmJYiVxTkepGiLu5DXAsl1r7ofY4ndvEfaP8975Q9zdEMZgxKGbqyIYKzcsKfIY7ogrWNAUp6g0E0YQGoEcMEldt21L2RpaGn17X4KhX//VaX1V5jpxNmerrySfho1QDCOaQSIxg4Q0nXLESkMovqlgDEO/R1JHPYrUpMLg2ANq86TEIeLPoIz/sI8dzAogxxefVjto2ES13+Tdu7YWM5Ho9DGKtnjEXVuhyKeCk6Udc4wTmgJJuXWV3Tg/cOcJjaGX3xtncGTxtYaky5jS4oDZVCeXAw1KPS8mR3tzbTGeZefKQLuBLJzmzzuR18M0xQOohwRinl0ZarcG9/m15Zc2uOjHJBkhKqsj1M6fp/POjQdKVh8kcVyX5CVUceVgiPMFbD5n08n6bbNap8rV8H8RyezHBrfn0Ys5IGCK15LAQLos67hCxOb65rnSuJaRJi5eUcU6A6PlE04cwW1otWOMe8zfVNArtTihEJmqXn1+HWAfCcuyrZDeGA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
